language: objective-c
xcode_project: TravisTest.xcodeproj
xcode_scheme: TravisTest
env:
  global:
  - KEY_PASSWORD="travis"
  - APP_NAME="TravisTest"
  - 'DEVELOPER_NAME="iPhone Distribution: Erik Villegas (4Y3DH4MJR2)"'
  - PROFILE_NAME="TravisTest_Ad_Hoc_Profile"
before_script:
- ./scripts/add-key.sh
script:
- xctool -project TravisTest.xcodeproj -scheme TravisTest -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
after_success:
- ./scripts/sign.sh
after_script:
- ./scripts/keychain.sh
